version: 2
jobs:
  build:
    working_directory: ~/spring-boot-examples/spring-boot-2-jdbc-with-h2
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
      path: ~/spring-boot-examples
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn package -DskipTests
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: ~/junit
workflows:
  version: 2
  build_test_deploy:
    jobs:
    - build:
        context: demo
        filters:
          branches:
            only: master