version: 2
aliases:
- &post_build
  name: Trigger down stream builds
  command: |
    echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
    echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
    echo 'export DEMO_GITHUB_TOKEN="$DEMO_GITHUB_TOKEN"' >> $BASH_ENV
    chmod +x ./.circleci/trigger_build.sh
    ./.circleci/trigger_build.sh "assadriaz/demo.git" "master" "$(git log -1 --pretty=%B)"
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn package -DskipTests
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: ~/junit
    - run: *post_build
workflows:
  version: 2
  build_test_deploy:
    jobs:
    - build:
        context: demo
        filters:
          branches:
            only: master